import type { Lesson } from "./schema";

export const deepLessons: Lesson[] = [
  {
    id: "arabic-reading-strategy",
    subjectId: "arabic",
    title: "العربية: فهم النص سؤالاً بسؤال",
    shortTitle: "فهم النص",
    durationMinutes: 30,
    difficulty: "repair",
    summary:
      "كيفاش تقرأي النص بدون ما تتوهي: عنوان، فكرة عامة، أفكار جزئية، ثم جواب على قد السؤال.",
    goals: [
      "تمييز الفكرة العامة عن التفاصيل",
      "استخراج سبب أو نتيجة من النص",
      "استعمال كلمة مفتاحية من النص داخل الجواب",
    ],
    phoneAwayRitual:
      "اقرئي العنوان أولاً، وغطي باقي الصفحة 30 ثانية. اسألي روحك: الموضوع على واش؟",
    recallWarmup:
      "اكتبي من الذاكرة الفرق بين الفكرة العامة والفكرة الجزئية في سطر واحد.",
    finishLine:
      "لازم تقدري تجاوبي على 3 أسئلة فهم من دون نسخ عشوائي ومن دون خروج عن المطلوب.",
    sections: [
      {
        title: "1) البداية الصحيحة",
        body: [
          "العنوان والجملة الأولى غالباً يعطيوك الباب الرئيسي للنص.",
          "قبل ما تقرأي كل سطر، حددي نوع السؤال: فكرة؟ سبب؟ نتيجة؟ موقف الكاتب؟",
        ],
      },
      {
        title: "2) كيف نلقاو الفكرة العامة",
        body: [
          "الفكرة العامة ماشي تفصيل صغير، بل المعنى اللي يجمع كامل النص.",
          "إذا قدرتي تبدلي بعض الكلمات بكلمات قريبة ويبقى نفس المعنى، راكي قريبة من الفكرة العامة.",
        ],
        callout: "الخطأ الشائع: كتابة عنوان النص فقط واعتباره فكرة عامة.",
      },
      {
        title: "3) السبب والنتيجة",
        body: [
          "سؤال السبب يجاوب على: لماذا؟ سؤال النتيجة يجاوب على: ماذا نتج؟",
          "في كثير من النصوص تلقاي روابط مثل: لأن، لذلك، لهذا، نتيجةً لـ.",
        ],
        bullets: ["سبب", "نتيجة", "تعليل", "استنتاج"],
      },
    ],
    practice: [
      {
        id: "ar-read-1",
        type: "multiple-choice",
        prompt: "إذا كان السؤال: ما الفكرة العامة؟ ماذا تختارين؟",
        choices: [
          { id: "a", label: "تفصيل صغير من فقرة واحدة" },
          { id: "b", label: "المعنى الذي يجمع النص كله" },
          { id: "c", label: "اسم الكاتب فقط" },
        ],
        correctChoiceId: "b",
        hints: ["الفكرة العامة تشمل النص، ماشي جملة معزولة."],
        explanation: "الفكرة العامة تلخص الاتجاه العام للنص كله.",
        sourceRefs: ["BEM Arabic archive 2016-2025"],
      },
      {
        id: "ar-read-2",
        type: "short-text",
        prompt: "إذا طلب السؤال السبب، ما الكلمة التي تبحثين عنها أولاً داخل النص؟",
        acceptedAnswers: ["لأن", "لان", "تعليل", "سبب"],
        hints: ["ابحثي عن رابط يفسر لماذا وقع الأمر."],
        explanation: "روابط التعليل مثل لأن تساعدك على تحديد جواب السبب بسرعة.",
        sourceRefs: ["4AM Arabic methodology"],
      },
      {
        id: "ar-read-3",
        type: "reorder",
        prompt: "رتبي منهجية فهم النص:",
        items: ["تحديد نوع السؤال", "قراءة العنوان والجملة الأولى", "استخراج الكلمة المفتاحية", "صياغة جواب مختصر"],
        correctOrder: ["قراءة العنوان والجملة الأولى", "تحديد نوع السؤال", "استخراج الكلمة المفتاحية", "صياغة جواب مختصر"],
        hints: ["الفهم يبدأ قبل الجواب."],
        explanation: "بهذا الترتيب تمنعي التسرع والنسخ العشوائي.",
        sourceRefs: ["Pedagogical docs Arabic 4AM"],
      },
    ],
    summarySheetId: "summary-arabic",
    sourceRefs: ["BEM Arabic archive 2016-2025", "Pedagogical docs Arabic 4AM"],
    examLinkYears: [2017, 2020, 2023, 2025],
    visual: "none",
  },
  {
    id: "french-reading-method",
    subjectId: "french",
    title: "Français: compréhension sans panique",
    shortTitle: "Compréhension",
    durationMinutes: 30,
    difficulty: "repair",
    summary:
      "Lire le titre, repérer le thème, chercher la phrase utile, puis répondre avec une phrase courte et correcte.",
    goals: [
      "Repérer le thème d'un texte",
      "Trouver l'idée essentielle",
      "Répondre avec une phrase complète",
    ],
    phoneAwayRitual: "Lis le titre, puis écris un seul mot sur le thème probable.",
    recallWarmup: "Écris une phrase simple avec le mot important.",
    finishLine: "Tu dois répondre à 3 questions de compréhension avec des phrases courtes mais propres.",
    sections: [
      {
        title: "1) Titre puis questions",
        body: [
          "Le titre te donne souvent le champ lexical principal du texte.",
          "Lis la question avant de relire le passage concerné.",
        ],
      },
      {
        title: "2) Repérer l'idée",
        body: [
          "L'idée essentielle n'est pas un détail isolé.",
          "Cherche ce que plusieurs phrases essaient de montrer ensemble.",
        ],
      },
      {
        title: "3) Réponse propre",
        body: [
          "Une phrase simple et juste vaut mieux qu'une longue phrase cassée.",
          "Quand c'est possible, reprends un mot du texte pour rester précis.",
        ],
      },
    ],
    practice: [
      {
        id: "fr-read-1",
        type: "multiple-choice",
        prompt: "Pour repérer le thème d'un texte, tu regardes d'abord...",
        choices: [
          { id: "a", label: "le titre" },
          { id: "b", label: "la dernière lettre" },
          { id: "c", label: "les notes seulement" },
        ],
        correctChoiceId: "a",
        hints: ["Le premier indice est visible avant la lecture complète."],
        explanation: "Le titre oriente le thème et le champ lexical.",
        sourceRefs: ["BEM French archive 2016-2025"],
      },
      {
        id: "fr-read-2",
        type: "short-text",
        prompt: "Complète avec une phrase correcte: Le thème du texte est ...",
        acceptedAnswers: [
          "Le thème du texte est l'école.",
          "Le thème du texte est la protection de l'environnement.",
        ],
        hints: ["Une phrase courte suffit."],
        explanation: "Le but est de répondre avec une structure simple et correcte.",
        sourceRefs: ["4AM French comprehension"],
      },
      {
        id: "fr-read-3",
        type: "multiple-choice",
        prompt: "Quelle réponse est la plus propre dans un examen ?",
        choices: [
          { id: "a", label: "Oui" },
          { id: "b", label: "La réponse complète et claire." },
          { id: "c", label: "Un mot isolé sans contexte." },
        ],
        correctChoiceId: "b",
        hints: ["Le correcteur doit comprendre immédiatement."],
        explanation: "Une phrase complète est plus sûre quand le contexte le demande.",
        sourceRefs: ["BEM French archive 2016-2025"],
      },
    ],
    summarySheetId: "summary-french",
    sourceRefs: ["BEM French archive 2016-2025", "4AM French summaries"],
    examLinkYears: [2016, 2019, 2022, 2025],
    visual: "none",
  },
  {
    id: "english-reading-vocabulary",
    subjectId: "english",
    title: "English: reading and vocabulary moves",
    shortTitle: "Reading",
    durationMinutes: 30,
    difficulty: "repair",
    summary:
      "How to find the topic, catch the main idea, and use the text vocabulary without getting lost.",
    goals: [
      "Find the topic quickly",
      "Answer from the text without copying blindly",
      "Use context to infer meaning",
    ],
    phoneAwayRitual: "Read the title and write one topic word before reading the whole text.",
    recallWarmup: "Write one sentence with school or environment.",
    finishLine: "You should answer short reading questions with confidence and clean English.",
    sections: [
      {
        title: "1) Title and first line",
        body: [
          "The title and first sentence usually reveal the topic.",
          "Do not start translating every word. Start by finding the general meaning.",
        ],
      },
      {
        title: "2) Main idea",
        body: [
          "The main idea is bigger than one detail.",
          "Ask: what is this text mainly trying to say?",
        ],
      },
      {
        title: "3) Vocabulary in context",
        body: [
          "A word can be understood from the sentence around it.",
          "Look at the idea before and after the word, not the word alone.",
        ],
      },
    ],
    practice: [
      {
        id: "en-read-1",
        type: "multiple-choice",
        prompt: "What helps you know the topic first?",
        choices: [
          { id: "a", label: "The title" },
          { id: "b", label: "The score" },
          { id: "c", label: "The punctuation only" },
        ],
        correctChoiceId: "a",
        hints: ["It is the first clear clue."],
        explanation: "The title often gives the topic immediately.",
        sourceRefs: ["BEM English archive 2016-2025"],
      },
      {
        id: "en-read-2",
        type: "short-text",
        prompt: "Complete: The main idea is the ... meaning of the text.",
        acceptedAnswers: ["general", "main", "overall"],
        hints: ["It is not one small detail."],
        explanation: "The main idea is the general or overall meaning.",
        sourceRefs: ["4AM English methodology"],
      },
      {
        id: "en-read-3",
        type: "multiple-choice",
        prompt: "When you do not know one word, you should...",
        choices: [
          { id: "a", label: "stop the whole reading" },
          { id: "b", label: "look at the sentence around it" },
          { id: "c", label: "skip the full exercise" },
        ],
        correctChoiceId: "b",
        hints: ["Context matters."],
        explanation: "Context helps infer meaning without panic.",
        sourceRefs: ["BEM English archive 2016-2025"],
      },
    ],
    summarySheetId: "summary-english",
    sourceRefs: ["BEM English archive 2016-2025", "4AM English summaries"],
    examLinkYears: [2016, 2018, 2021, 2024],
    visual: "none",
  },
  {
    id: "history-dates-core",
    subjectId: "historygeo",
    title: "تاريخ: التواريخ الأساسية بدون خلط",
    shortTitle: "التواريخ الأساسية",
    durationMinutes: 30,
    difficulty: "repair",
    summary:
      "بناء عمود فقري ثابت للتاريخ الوطني: 1830، 1931، 1945، 1954، 1956، 1958، 1962 وما بعده.",
    goals: [
      "تثبيت التواريخ المفصلية",
      "ربط كل تاريخ بحدث واحد واضح",
      "منع الخلط بين 19 مارس و05 جويلية",
    ],
    phoneAwayRitual: "اكتبي 4 تواريخ من الذاكرة قبل ما تشوفي الدرس.",
    recallWarmup: "ما الحدث المرتبط بـ 01 نوفمبر 1954؟",
    finishLine: "لازم تقدري تذكري 8 تواريخ أساسية مع الحدث المرتبط بكل واحد.",
    sections: [
      {
        title: "1) العمود الفقري",
        body: [
          "14 جوان 1830: بداية الاحتلال الفرنسي.",
          "05 ماي 1931: تأسيس جمعية العلماء المسلمين الجزائريين.",
          "08 ماي 1945: المجازر.",
          "01 نوفمبر 1954: اندلاع الثورة التحريرية.",
        ],
      },
      {
        title: "2) تواريخ الثورة",
        body: [
          "20 أوت 1956: مؤتمر الصومام.",
          "19 سبتمبر 1958: الحكومة المؤقتة للجمهورية الجزائرية.",
          "19 مارس 1962: وقف إطلاق النار بعد اتفاقيات إيفيان.",
          "05 جويلية 1962: الاستقلال.",
        ],
        callout: "19 مارس ليس هو الاستقلال. الاستقلال هو 05 جويلية 1962.",
      },
    ],
    practice: [
      {
        id: "hg-date-1",
        type: "short-text",
        prompt: "ما الحدث المرتبط بتاريخ 08 ماي 1945؟",
        acceptedAnswers: [
          "مجازر 8 ماي 1945",
          "المجازر",
          "مجازر سطيف وقالمة وخراطة",
        ],
        hints: ["حدث مفصلي قبل الثورة المسلحة."],
        explanation: "هذا التاريخ مرتبط بالمجازر التي عمقت القطيعة مع الاستعمار.",
        sourceRefs: ["BEM History/Geo archive 2016-2025"],
      },
      {
        id: "hg-date-2",
        type: "reorder",
        prompt: "رتبي هذه التواريخ:",
        items: ["05 جويلية 1962", "01 نوفمبر 1954", "19 سبتمبر 1958", "08 ماي 1945"],
        correctOrder: ["08 ماي 1945", "01 نوفمبر 1954", "19 سبتمبر 1958", "05 جويلية 1962"],
        hints: ["1945 ثم 1954 ثم 1958 ثم 1962."],
        explanation: "هذا الترتيب يساعد على تثبيت السلسلة الأساسية للثورة والتحرير.",
        sourceRefs: ["BEM History/Geo archive 2016-2025"],
      },
      {
        id: "hg-date-3",
        type: "multiple-choice",
        prompt: "أي تاريخ يمثل وقف إطلاق النار؟",
        choices: [
          { id: "a", label: "19 مارس 1962" },
          { id: "b", label: "05 جويلية 1962" },
          { id: "c", label: "20 أوت 1956" },
        ],
        correctChoiceId: "a",
        hints: ["ليس هو تاريخ الاستقلال."],
        explanation: "19 مارس 1962 يرتبط باتفاقيات إيفيان ووقف إطلاق النار.",
        sourceRefs: ["BEM History/Geo archive 2016-2025"],
      },
    ],
    summarySheetId: "summary-history-dates",
    sourceRefs: ["BEM History/Geo archive 2016-2025"],
    examLinkYears: [2016, 2019, 2021, 2025],
    visual: "none",
  },
  {
    id: "physics-electricity",
    subjectId: "physics",
    title: "فيزياء: الكهرباء خطوة بخطوة",
    shortTitle: "الكهرباء",
    durationMinutes: 30,
    difficulty: "repair",
    summary:
      "شدة التيار، التوتر، المقاومة، وقانون أوم مع روتين ثابت يمنع التخليط.",
    goals: [
      "تمييز الرموز الكهربائية",
      "اختيار القانون المناسب",
      "الحفاظ على الوحدات داخل الجواب",
    ],
    phoneAwayRitual: "اكتبي جدولاً صغيراً: U / I / R ومعنى كل رمز.",
    recallWarmup: "ما قانون أوم؟ اكتبيه من الذاكرة.",
    finishLine: "لازم تقدري تحلي تمرين كهرباء بسيط من غير خلط بين U و I و R.",
    sections: [
      {
        title: "1) الرموز أولاً",
        body: [
          "U للتوتر، I لشدة التيار، R للمقاومة.",
          "إذا خلطتي الرموز من البداية، الحساب كامل يضيع.",
        ],
      },
      {
        title: "2) قانون أوم",
        body: [
          "القانون الأشهر هنا: U = R × I.",
          "ومن نفس العلاقة نقدر نكتب I = U / R و R = U / I حسب المطلوب.",
        ],
      },
      {
        title: "3) الوحدات",
        body: [
          "التوتر بالفولت V، الشدة بالأمبير A، المقاومة بالأوم Ω.",
          "الوحدة جزء من الجواب النهائي، ماشي تفصيل إضافي.",
        ],
      },
    ],
    practice: [
      {
        id: "phy-elec-1",
        type: "number",
        prompt: "إذا كانت R = 4 Ω و I = 3 A، ما قيمة U؟",
        answer: 12,
        suffix: "V",
        hints: ["استعملي U = R × I."],
        explanation: "4 × 3 = 12 V.",
        sourceRefs: ["BEM Physics archive 2016-2025"],
      },
      {
        id: "phy-elec-2",
        type: "multiple-choice",
        prompt: "ما رمز شدة التيار؟",
        choices: [
          { id: "a", label: "U" },
          { id: "b", label: "I" },
          { id: "c", label: "R" },
        ],
        correctChoiceId: "b",
        hints: ["فكري في الأمبير."],
        explanation: "I هو رمز شدة التيار الكهربائي.",
        sourceRefs: ["4AM Physics electricity"],
      },
      {
        id: "phy-elec-3",
        type: "short-text",
        prompt: "ما وحدة المقاومة الكهربائية؟",
        acceptedAnswers: ["الأوم", "اوم", "Ω"],
        hints: ["ليست الفولت ولا الأمبير."],
        explanation: "المقاومة تقاس بالأوم Ω.",
        sourceRefs: ["BEM Physics archive 2016-2025"],
      },
    ],
    summarySheetId: "summary-physics",
    sourceRefs: ["BEM Physics archive 2016-2025", "4AM Physics electricity"],
    examLinkYears: [2017, 2020, 2023, 2025],
    visual: "none",
  },
  {
    id: "science-nervous-immunity",
    subjectId: "science",
    title: "علوم: الجهاز العصبي والمناعة كسلاسل",
    shortTitle: "العصبي والمناعة",
    durationMinutes: 30,
    difficulty: "repair",
    summary:
      "نحوّل الدرس إلى سلسلة واضحة: منبه -> معالجة -> استجابة، أو جسم غريب -> دفاع -> حماية.",
    goals: [
      "فهم المسار العصبي",
      "تثبيت دور الأجسام الدفاعية",
      "الإجابة بجمل علمية قصيرة",
    ],
    phoneAwayRitual: "ارسمي سهماً بين كل مرحلة وأخرى قبل القراءة.",
    recallWarmup: "ما الذي يأتي بعد المستقبل الحسي؟",
    finishLine: "لازم تقدري تشرحي آلية قصيرة على شكل مراحل متتابعة.",
    sections: [
      {
        title: "1) السلسلة العصبية",
        body: [
          "منبه -> مستقبل حسي -> عصب -> مركز عصبي -> استجابة.",
          "هذه السلسلة أهم من حفظ فقرة طويلة مشتتة.",
        ],
      },
      {
        title: "2) المناعة",
        body: [
          "الجسم الغريب يستفز دفاعاً داخل الجسم.",
          "الفكرة الأساسية: تعرف الجسم على الخطر ثم مقاومته ثم الحماية.",
        ],
      },
      {
        title: "3) التعبير العلمي",
        body: [
          "استعملي كلمات مثل: ينتقل، يستجيب، يدافع، يحمي.",
          "لا تحاولي الزخرفة. الجواب العلمي الواضح أفضل.",
        ],
      },
    ],
    practice: [
      {
        id: "sci-neu-1",
        type: "reorder",
        prompt: "رتبي مراحل السلسلة العصبية:",
        items: ["مركز عصبي", "منبه", "استجابة", "مستقبل حسي", "عصب"],
        correctOrder: ["منبه", "مستقبل حسي", "عصب", "مركز عصبي", "استجابة"],
        hints: ["ابحثي عن نقطة البداية ونقطة النهاية."],
        explanation: "بهذا التسلسل تنتقل الرسالة العصبية بشكل منظم.",
        sourceRefs: ["BEM Science archive 2016-2025"],
      },
      {
        id: "sci-neu-2",
        type: "short-text",
        prompt: "ما الفكرة العامة للمناعة في كلمة أو كلمتين؟",
        acceptedAnswers: ["الدفاع", "حماية الجسم", "الدفاع عن الجسم"],
        hints: ["المناعة تحمي الجسم."],
        explanation: "المناعة هي نظام دفاع وحماية للجسم.",
        sourceRefs: ["4AM Science immunity"],
      },
      {
        id: "sci-neu-3",
        type: "multiple-choice",
        prompt: "في السلسلة العصبية، من يسبق الاستجابة مباشرة؟",
        choices: [
          { id: "a", label: "المركز العصبي" },
          { id: "b", label: "المنبه" },
          { id: "c", label: "الجسم الغريب" },
        ],
        correctChoiceId: "a",
        hints: ["راجعي الترتيب الكامل."],
        explanation: "بعد المركز العصبي تأتي الاستجابة.",
        sourceRefs: ["BEM Science archive 2016-2025"],
      },
    ],
    summarySheetId: "summary-science",
    sourceRefs: ["BEM Science archive 2016-2025", "4AM Science summaries"],
    examLinkYears: [2017, 2020, 2023, 2025],
    visual: "none",
  },
  {
    id: "islamic-meanings",
    subjectId: "islamic",
    title: "إسلامية: استخراج المعنى والعبرة",
    shortTitle: "المعنى والعبرة",
    durationMinutes: 25,
    difficulty: "repair",
    summary:
      "نفرق بين معنى النص، القيمة التي يحملها، والعبرة أو الفائدة المطلوبة في الجواب.",
    goals: [
      "تحديد المعنى العام",
      "استخراج قيمة أخلاقية أو سلوكية",
      "صياغة العبرة بجملة واضحة",
    ],
    phoneAwayRitual: "اكتبي ثلاث خانات: معنى / قيمة / عبرة.",
    recallWarmup: "ما قيمة أخلاقية تحفظينها من دروس الإسلامية؟",
    finishLine: "لازم تقدري تفرقي بين معنى النص وبين القيمة التي يستخرجها السؤال.",
    sections: [
      {
        title: "1) معنى النص",
        body: [
          "المعنى يشرح المقصود العام للنص أو الآية أو الحديث.",
          "لا تطيلي هنا. المطلوب غالباً جملة واضحة ومباشرة.",
        ],
      },
      {
        title: "2) القيمة",
        body: [
          "القيمة تكون مثل الصدق، الأمانة، التعاون، الرحمة، المسؤولية.",
          "القيمة ليست شرحاً طويلاً بل تسمية صحيحة مدعومة بفهم.",
        ],
      },
      {
        title: "3) العبرة أو الفائدة",
        body: [
          "العبرة تبين ما الذي نتعلمه أو نطبقه من النص.",
          "هنا نربط المعنى بالحياة اليومية.",
        ],
      },
    ],
    practice: [
      {
        id: "isl-mean-1",
        type: "multiple-choice",
        prompt: "إذا طلب السؤال قيمة أخلاقية، فأنت تبحثين عن...",
        choices: [
          { id: "a", label: "اسم قيمة مثل الأمانة" },
          { id: "b", label: "تاريخ حدث" },
          { id: "c", label: "قانون رياضي" },
        ],
        correctChoiceId: "a",
        hints: ["السؤال هنا ليس عن التاريخ ولا الحساب."],
        explanation: "القيمة هي خلق أو مبدأ سلوكي يستفاد من النص.",
        sourceRefs: ["BEM Islamic archive 2016-2025"],
      },
      {
        id: "isl-mean-2",
        type: "short-text",
        prompt: "إذا كان النص يدعو إلى قول الحق، فما القيمة المناسبة؟",
        acceptedAnswers: ["الصدق", "صدق", "قيمة الصدق"],
        hints: ["فكري في الخلق المناسب."],
        explanation: "قول الحق يرتبط بقيمة الصدق.",
        sourceRefs: ["4AM Islamic studies"],
      },
      {
        id: "isl-mean-3",
        type: "short-text",
        prompt: "ما المطلوب في العبرة؟",
        acceptedAnswers: [
          "ما نتعلمه من النص",
          "الفائدة التي نتعلمها",
          "الدرس المستفاد",
        ],
        hints: ["هي ليست مجرد تكرار للمعنى."],
        explanation: "العبرة هي الدرس المستفاد القابل للتطبيق.",
        sourceRefs: ["BEM Islamic archive 2016-2025"],
      },
    ],
    summarySheetId: "summary-islamic",
    sourceRefs: ["BEM Islamic archive 2016-2025", "4AM Islamic studies"],
    examLinkYears: [2016, 2019, 2022, 2025],
    visual: "none",
  },
  {
    id: "civics-rights-duties",
    subjectId: "civics",
    title: "مدنية: الحقوق والواجبات بدون خلط",
    shortTitle: "الحقوق والواجبات",
    durationMinutes: 25,
    difficulty: "repair",
    summary:
      "التمييز بين الحق والواجب مع أمثلة قريبة من الحياة اليومية حتى يثبت المفهوم.",
    goals: [
      "تمييز الحق عن الواجب",
      "ربط كل مفهوم بمثال",
      "منع الخلط في أسئلة الاختيار",
    ],
    phoneAwayRitual: "اكتبي مثالين: حق / واجب.",
    recallWarmup: "هل التمدرس حق أم واجب؟ وما احترام القانون؟",
    finishLine: "لازم تقدري تصنفي أمثلة شائعة بسرعة إلى حقوق أو واجبات.",
    sections: [
      {
        title: "1) ما هو الحق",
        body: [
          "الحق هو شيء يضمنه المجتمع أو القانون للفرد مثل التعليم والحماية والصحة.",
          "الحق تستفيد منه، لكنه لا يلغي الواجبات.",
        ],
      },
      {
        title: "2) ما هو الواجب",
        body: [
          "الواجب هو ما يجب على المواطن القيام به مثل احترام القانون والمحافظة على الممتلكات العامة.",
          "الواجب يضمن حسن العيش المشترك.",
        ],
      },
      {
        title: "3) المثال هو المفتاح",
        body: [
          "إذا حفظت المفهوم مع مثال، تقل الأخطاء كثيراً.",
          "مثال: التمدرس حق، احترام القانون واجب.",
        ],
      },
    ],
    practice: [
      {
        id: "civ-rd-1",
        type: "multiple-choice",
        prompt: "التمدرس يمثل...",
        choices: [
          { id: "a", label: "حقاً" },
          { id: "b", label: "واجباً" },
          { id: "c", label: "قانوناً رياضياً" },
        ],
        correctChoiceId: "a",
        hints: ["فكري في ما يستفيد منه المواطن."],
        explanation: "التمدرس من الحقوق الأساسية للمواطن.",
        sourceRefs: ["BEM Civics archive 2016-2025"],
      },
      {
        id: "civ-rd-2",
        type: "multiple-choice",
        prompt: "احترام القانون يمثل...",
        choices: [
          { id: "a", label: "حقاً" },
          { id: "b", label: "واجباً" },
          { id: "c", label: "مجرد رأي" },
        ],
        correctChoiceId: "b",
        hints: ["هو ما يجب فعله."],
        explanation: "احترام القانون من واجبات المواطن.",
        sourceRefs: ["BEM Civics archive 2016-2025"],
      },
      {
        id: "civ-rd-3",
        type: "multi-select",
        prompt: "اختاري ما يدخل ضمن الواجبات:",
        choices: [
          { id: "a", label: "احترام القانون" },
          { id: "b", label: "المحافظة على الممتلكات العامة" },
          { id: "c", label: "التمدرس" },
        ],
        correctChoiceIds: ["a", "b"],
        hints: ["الواجب هو ما يجب القيام به."],
        explanation: "الحق تستفيد منه، والواجب تؤدينه وتحافظين عليه.",
        sourceRefs: ["BEM Civics archive 2016-2025"],
      },
    ],
    summarySheetId: "summary-civics",
    sourceRefs: ["BEM Civics archive 2016-2025", "4AM Civics"],
    examLinkYears: [2017, 2020, 2022, 2025],
    visual: "none",
  },
];
