import type { ExamSection, SubjectId } from "./schema";

const guidedExamSections: Partial<Record<SubjectId, ExamSection[]>> = {
  arabic: [
    {
      title: "فهم النص",
      note: "الفكرة العامة، التعليل، وطريقة الجواب الواضح.",
      questions: [
        {
          id: "ar-exam-read-1",
          type: "multiple-choice",
          prompt: "في سؤال الفكرة العامة، ماذا نبحث عادة؟",
          choices: [
            { id: "a", label: "تفصيل صغير في سطر واحد" },
            { id: "b", label: "المعنى الذي يجمع النص كله" },
            { id: "c", label: "اسم الكاتب فقط" },
          ],
          correctChoiceId: "b",
          hints: ["الفكرة العامة أوسع من التفصيل."],
          explanation: "الفكرة العامة تلخص اتجاه النص كاملاً.",
          sourceRefs: ["BEM Arabic archive 2016-2025"],
        },
        {
          id: "ar-exam-read-2",
          type: "short-text",
          prompt: "إذا طلب منك السبب، ما نوع العبارة التي تبحثين عنها؟",
          acceptedAnswers: [
            "الجملة التي تفسر السبب",
            "عبارة التعليل",
            "ما يفسر لماذا",
          ],
          hints: ["السبب يجيب عن لماذا."],
          explanation: "جواب السبب يلتقط عبارة التعليل أو التفسير داخل النص.",
          sourceRefs: ["BEM Arabic archive 2016-2025"],
        },
      ],
    },
    {
      title: "اللغة",
      note: "نوع الجملة، الوظيفة، والأسلوب.",
      questions: [
        {
          id: "ar-exam-lang-1",
          type: "multiple-choice",
          prompt: "الجملة: لا تهمل واجباتك. ما الأسلوب؟",
          choices: [
            { id: "a", label: "نهي" },
            { id: "b", label: "استفهام" },
            { id: "c", label: "تعجب" },
          ],
          correctChoiceId: "a",
          hints: ["وجود لا مع الفعل مهم هنا."],
          explanation: "لا تهمل أسلوب نهي لأنه يطلب الكف عن الفعل.",
          sourceRefs: ["BEM Arabic archive 2016-2025"],
        },
        {
          id: "ar-exam-lang-2",
          type: "short-text",
          prompt: "في الجملة: العلم نور، ما وظيفة كلمة نور؟",
          acceptedAnswers: ["خبر", "الخبر"],
          hints: ["هي التي تتمم معنى المبتدأ."],
          explanation: "نور خبر لأنه أتم معنى المبتدأ العلم.",
          sourceRefs: ["4AM Arabic grammar"],
        },
      ],
    },
    {
      title: "التعبير الكتابي",
      note: "تنظيم الفقرة والجواب على قد المطلوب.",
      questions: [
        {
          id: "ar-exam-write-1",
          type: "reorder",
          prompt: "رتبي بناء فقرة قصيرة:",
          items: ["خاتمة بسيطة", "مقدمة قصيرة", "فكرة داعمة"],
          correctOrder: ["مقدمة قصيرة", "فكرة داعمة", "خاتمة بسيطة"],
          hints: ["ابدئي بالموضوع ثم دعميه ثم اختمي."],
          explanation: "هذا التنظيم يجعل التعبير واضحاً وسهل القراءة.",
          sourceRefs: ["BEM Arabic archive 2016-2025"],
        },
        {
          id: "ar-exam-write-2",
          type: "short-text",
          prompt: "اكتبي افتتاحية قصيرة لموضوع عن أهمية الدراسة.",
          acceptedAnswers: [
            "الدراسة أساس النجاح في حياة التلميذ.",
            "الدراسة مهمة في حياة الإنسان.",
          ],
          hints: ["جملة واضحة تكفي."],
          explanation: "المقدمة الجيدة تكون مباشرة وواضحة من دون حشو.",
          sourceRefs: ["BEM Arabic archive 2016-2025"],
        },
      ],
    },
  ],
  french: [
    {
      title: "Compréhension",
      note: "Thème, idée, et réponse correcte.",
      questions: [
        {
          id: "fr-exam-read-1",
          type: "multiple-choice",
          prompt: "Pour trouver le thème d'un texte, tu regardes d'abord...",
          choices: [
            { id: "a", label: "le titre" },
            { id: "b", label: "la signature" },
            { id: "c", label: "les marques de ponctuation seulement" },
          ],
          correctChoiceId: "a",
          hints: ["Le premier indice est en haut du texte."],
          explanation: "Le titre oriente la lecture et le thème.",
          sourceRefs: ["BEM French archive 2016-2025"],
        },
        {
          id: "fr-exam-read-2",
          type: "short-text",
          prompt: "Écris une réponse complète: Le thème du texte est ...",
          acceptedAnswers: [
            "Le thème du texte est l'environnement.",
            "Le thème du texte est l'école.",
          ],
          hints: ["Une phrase simple suffit."],
          explanation: "Le correcteur attend une réponse courte mais correcte.",
          sourceRefs: ["BEM French archive 2016-2025"],
        },
      ],
    },
    {
      title: "Langue",
      note: "Connecteurs, condition, et structures fréquentes.",
      questions: [
        {
          id: "fr-exam-lang-1",
          type: "multiple-choice",
          prompt: "Quel connecteur exprime une conséquence ?",
          choices: [
            { id: "a", label: "parce que" },
            { id: "b", label: "donc" },
            { id: "c", label: "si" },
          ],
          correctChoiceId: "b",
          hints: ["La conséquence vient après le résultat."],
          explanation: "donc exprime une conséquence.",
          sourceRefs: ["BEM French archive 2016-2025"],
        },
        {
          id: "fr-exam-lang-2",
          type: "multiple-choice",
          prompt: "Choisis la phrase correcte.",
          choices: [
            { id: "a", label: "Si j'étudie, je réussirai." },
            { id: "b", label: "Si j'étudie, je réussirais." },
            { id: "c", label: "Si j'étudiais, je réussis." },
          ],
          correctChoiceId: "a",
          hints: ["Pense à la structure la plus sûre."],
          explanation: "Si + présent prend ici le futur dans la principale.",
          sourceRefs: ["4AM French grammar"],
        },
      ],
    },
    {
      title: "Production écrite",
      note: "Petit avis structuré et simple.",
      questions: [
        {
          id: "fr-exam-write-1",
          type: "short-text",
          prompt: "Complète: A mon avis, réviser chaque jour ...",
          acceptedAnswers: [
            "A mon avis, réviser chaque jour est utile.",
            "a mon avis, réviser chaque jour est utile.",
          ],
          hints: ["Donne un avis simple."],
          explanation: "Une phrase claire et correcte est suffisante.",
          sourceRefs: ["BEM French archive 2016-2025"],
        },
        {
          id: "fr-exam-write-2",
          type: "reorder",
          prompt: "Range les parties du petit paragraphe:",
          items: ["Conclusion courte", "Avis", "Raison"],
          correctOrder: ["Avis", "Raison", "Conclusion courte"],
          hints: ["L'avis vient avant l'argument."],
          explanation: "Cette structure garde la production écrite claire.",
          sourceRefs: ["BEM French archive 2016-2025"],
        },
      ],
    },
  ],
  english: [
    {
      title: "Reading",
      note: "Topic, main idea, and careful answers.",
      questions: [
        {
          id: "en-exam-read-1",
          type: "multiple-choice",
          prompt: "What helps you know the topic first?",
          choices: [
            { id: "a", label: "The title" },
            { id: "b", label: "The mark" },
            { id: "c", label: "The last word only" },
          ],
          correctChoiceId: "a",
          hints: ["It is the first visible clue."],
          explanation: "The title often tells you the topic quickly.",
          sourceRefs: ["BEM English archive 2016-2025"],
        },
        {
          id: "en-exam-read-2",
          type: "short-text",
          prompt: "Complete: The main idea is the ... meaning of the text.",
          acceptedAnswers: ["general", "overall", "main"],
          hints: ["It is bigger than one detail."],
          explanation: "The main idea is the general meaning of the text.",
          sourceRefs: ["BEM English archive 2016-2025"],
        },
      ],
    },
    {
      title: "Language",
      note: "Connectors and sentence building.",
      questions: [
        {
          id: "en-exam-lang-1",
          type: "multiple-choice",
          prompt: "Which connector gives a reason?",
          choices: [
            { id: "a", label: "because" },
            { id: "b", label: "but" },
            { id: "c", label: "so" },
          ],
          correctChoiceId: "a",
          hints: ["A reason answers why."],
          explanation: "because introduces a reason.",
          sourceRefs: ["BEM English archive 2016-2025"],
        },
        {
          id: "en-exam-lang-2",
          type: "short-text",
          prompt: "Write one correct sentence with because.",
          acceptedAnswers: [
            "I study because I want to succeed.",
            "i study because i want to succeed",
          ],
          hints: ["Keep it short and correct."],
          explanation: "Short clean sentences are strong in exam writing.",
          sourceRefs: ["4AM English writing"],
        },
      ],
    },
    {
      title: "Writing",
      note: "A short paragraph with a safe structure.",
      questions: [
        {
          id: "en-exam-write-1",
          type: "reorder",
          prompt: "Order the paragraph parts:",
          items: ["Topic sentence", "Supporting sentence", "Ending sentence"],
          correctOrder: ["Topic sentence", "Supporting sentence", "Ending sentence"],
          hints: ["Start general, then support, then close."],
          explanation: "This order makes the paragraph easy to follow.",
          sourceRefs: ["BEM English archive 2016-2025"],
        },
        {
          id: "en-exam-write-2",
          type: "short-text",
          prompt: "Write one piece of advice about phone use.",
          acceptedAnswers: [
            "You should put your phone away while studying.",
            "you should put your phone away while studying",
          ],
          hints: ["Use should + verb."],
          explanation: "This is a clear advice sentence with the right structure.",
          sourceRefs: ["BEM English archive 2016-2025"],
        },
      ],
    },
  ],
  historygeo: [
    {
      title: "Chronology",
      note: "Ordering dates and fixing the key milestones.",
      questions: [
        {
          id: "hg-exam-chrono-1",
          type: "reorder",
          prompt: "رتبي المحطات التالية:",
          items: ["الاستقلال", "مجازر 8 ماي 1945", "اندلاع الثورة التحريرية", "بداية الاحتلال"],
          correctOrder: ["بداية الاحتلال", "مجازر 8 ماي 1945", "اندلاع الثورة التحريرية", "الاستقلال"],
          hints: ["1830 ثم 1945 ثم 1954 ثم 1962."],
          explanation: "هذا هو التسلسل الذي يجب أن يثبت في الذاكرة.",
          sourceRefs: ["BEM History/Geo archive 2016-2025"],
        },
        {
          id: "hg-exam-chrono-2",
          type: "multiple-choice",
          prompt: "أي تاريخ يمثل وقف إطلاق النار؟",
          choices: [
            { id: "a", label: "19 مارس 1962" },
            { id: "b", label: "05 جويلية 1962" },
            { id: "c", label: "20 أوت 1956" },
          ],
          correctChoiceId: "a",
          hints: ["ليس هو الاستقلال."],
          explanation: "19 مارس 1962 يرتبط بإيفيان ووقف إطلاق النار.",
          sourceRefs: ["BEM History/Geo archive 2016-2025"],
        },
      ],
    },
    {
      title: "Cause and effect",
      note: "Why an event mattered and what it changed.",
      questions: [
        {
          id: "hg-exam-cause-1",
          type: "short-text",
          prompt: "لماذا تعتبر مجازر 8 ماي 1945 حدثاً مفصلياً؟",
          acceptedAnswers: [
            "لأنها عمقت القطيعة مع الاستعمار",
            "بينت عنف الاستعمار وعمقت القطيعة",
            "لأنها دفعت نحو الكفاح المسلح",
          ],
          hints: ["اذكري السبب والنتيجة إن أمكن."],
          explanation: "هذا الحدث كشف عنف الاستعمار وعمق رفض الحلول السلمية وحدها.",
          sourceRefs: ["BEM History/Geo archive 2016-2025"],
        },
        {
          id: "hg-exam-cause-2",
          type: "multiple-choice",
          prompt: "ما أهمية مؤتمر الصومام غالباً في الدروس؟",
          choices: [
            { id: "a", label: "تنظيم الثورة سياسياً وعسكرياً" },
            { id: "b", label: "بداية الاحتلال" },
            { id: "c", label: "تاريخ الاستقلال" },
          ],
          correctChoiceId: "a",
          hints: ["فكري في كلمة تنظيم."],
          explanation: "مؤتمر الصومام شكل محطة تنظيمية مركزية داخل الثورة.",
          sourceRefs: ["BEM History/Geo archive 2016-2025"],
        },
      ],
    },
    {
      title: "Geography and method",
      note: "Definitions, examples, and clear method.",
      questions: [
        {
          id: "hg-exam-geo-1",
          type: "multiple-choice",
          prompt: "أي مثال يرتبط بالموارد الطاقوية في الجزائر؟",
          choices: [
            { id: "a", label: "النفط والغاز" },
            { id: "b", label: "التعبير الكتابي" },
            { id: "c", label: "علامات الترقيم" },
          ],
          correctChoiceId: "a",
          hints: ["فكري في الثروات الطبيعية."],
          explanation: "النفط والغاز من أبرز الموارد الطاقوية في الجزائر.",
          sourceRefs: ["BEM History/Geo archive 2016-2025"],
        },
        {
          id: "hg-exam-geo-2",
          type: "short-text",
          prompt: "إذا طلب تعريف التنمية، كيف يكون الجواب المختصر؟",
          acceptedAnswers: [
            "تحسين الظروف الاقتصادية والاجتماعية",
            "هي تحسين الظروف الاقتصادية والاجتماعية",
          ],
          hints: ["الجواب يكون فكرة شاملة لا مثالاً فقط."],
          explanation: "التنمية ترتبط بتحسين ظروف الحياة والقدرات الاقتصادية والاجتماعية.",
          sourceRefs: ["BEM History/Geo archive 2016-2025"],
        },
      ],
    },
  ],
  physics: [
    {
      title: "الكهرباء",
      note: "قانون أوم، الرموز، والوحدات.",
      questions: [
        {
          id: "phy-exam-elec-1",
          type: "number",
          prompt: "إذا كانت R = 5 Ω و I = 2 A، ما قيمة U؟",
          answer: 10,
          suffix: "V",
          hints: ["استعمل U = R × I."],
          explanation: "5 × 2 = 10 V.",
          sourceRefs: ["BEM Physics archive 2016-2025"],
        },
        {
          id: "phy-exam-elec-2",
          type: "multiple-choice",
          prompt: "ما رمز شدة التيار الكهربائي؟",
          choices: [
            { id: "a", label: "I" },
            { id: "b", label: "R" },
            { id: "c", label: "U" },
          ],
          correctChoiceId: "a",
          hints: ["يرتبط بالأمبير."],
          explanation: "I هو رمز شدة التيار الكهربائي.",
          sourceRefs: ["BEM Physics archive 2016-2025"],
        },
      ],
    },
    {
      title: "الحركة",
      note: "السرعة، المسافة، والزمن.",
      questions: [
        {
          id: "phy-exam-motion-1",
          type: "number",
          prompt: "جسم قطع 120 m في 20 s. ما السرعة؟",
          answer: 6,
          suffix: "m/s",
          hints: ["استعمل v = d / t."],
          explanation: "120 ÷ 20 = 6 m/s.",
          sourceRefs: ["BEM Physics archive 2016-2025"],
        },
        {
          id: "phy-exam-motion-2",
          type: "multiple-choice",
          prompt: "إذا بقيت المسافة نفسها ونقص الزمن، فالسرعة...",
          choices: [
            { id: "a", label: "تنقص" },
            { id: "b", label: "تزيد" },
            { id: "c", label: "تبقى نفسها" },
          ],
          correctChoiceId: "b",
          hints: ["قسمة نفس العدد على زمن أصغر."],
          explanation: "مع نفس المسافة، نقص الزمن يعني سرعة أكبر.",
          sourceRefs: ["BEM Physics archive 2016-2025"],
        },
      ],
    },
    {
      title: "منهجية الحل",
      note: "القانون ثم التعويض ثم الوحدة.",
      questions: [
        {
          id: "phy-exam-method-1",
          type: "short-text",
          prompt: "ما أول خطوة قبل التعويض العددي؟",
          acceptedAnswers: ["كتابة القانون", "القانون", "نكتب القانون"],
          hints: ["لا تبدأ مباشرة بالأرقام."],
          explanation: "كتابة القانون أولاً توضح الفكرة وتمنع الخلط.",
          sourceRefs: ["Pedagogical docs Physics 4AM"],
        },
        {
          id: "phy-exam-method-2",
          type: "multiple-choice",
          prompt: "لماذا الوحدة مهمة في الجواب؟",
          choices: [
            { id: "a", label: "لأن الجواب بدون وحدة ناقص" },
            { id: "b", label: "لأنها تزين الورقة" },
            { id: "c", label: "ليست مهمة" },
          ],
          correctChoiceId: "a",
          hints: ["الوحدة جزء من المعنى الفيزيائي."],
          explanation: "النتيجة الفيزيائية لا تكتمل عادة بدون وحدتها.",
          sourceRefs: ["BEM Physics archive 2016-2025"],
        },
      ],
    },
  ],
  science: [
    {
      title: "السلسلة العصبية",
      note: "ترتيب المراحل الأساسية في الاستجابة العصبية.",
      questions: [
        {
          id: "sci-exam-neuro-1",
          type: "reorder",
          prompt: "رتبي مراحل السلسلة العصبية:",
          items: ["مركز عصبي", "منبه", "استجابة", "مستقبل حسي", "عصب"],
          correctOrder: ["منبه", "مستقبل حسي", "عصب", "مركز عصبي", "استجابة"],
          hints: ["ابدئي بما يحفز الجسم."],
          explanation: "بهذا الترتيب تنتقل الرسالة العصبية بشكل سليم.",
          sourceRefs: ["BEM Science archive 2016-2025"],
        },
        {
          id: "sci-exam-neuro-2",
          type: "short-text",
          prompt: "ما الذي يأتي بعد المستقبل الحسي؟",
          acceptedAnswers: ["العصب", "عصب"],
          hints: ["فكري في مسار الرسالة."],
          explanation: "بعد المستقبل الحسي تنتقل الرسالة عبر عصب.",
          sourceRefs: ["BEM Science archive 2016-2025"],
        },
      ],
    },
    {
      title: "المناعة",
      note: "الفكرة العامة للدفاع عن الجسم.",
      questions: [
        {
          id: "sci-exam-imm-1",
          type: "short-text",
          prompt: "في كلمة أو كلمتين: ما وظيفة المناعة؟",
          acceptedAnswers: ["حماية الجسم", "الدفاع عن الجسم", "الدفاع"],
          hints: ["المناعة تواجه الخطر."],
          explanation: "المناعة هي دفاع الجسم ضد الأخطار والعوامل الغريبة.",
          sourceRefs: ["BEM Science archive 2016-2025"],
        },
        {
          id: "sci-exam-imm-2",
          type: "multiple-choice",
          prompt: "أي فكرة تمثل فهم المناعة؟",
          choices: [
            { id: "a", label: "تعرف الخطر ثم الدفاع عنه" },
            { id: "b", label: "مجرد حفظ أسماء فقط" },
            { id: "c", label: "إلغاء دور الجسم" },
          ],
          correctChoiceId: "a",
          hints: ["المناعة آلية وليست لائحة فقط."],
          explanation: "المناعة تقوم على تعرف الجسم على الخطر ثم مقاومته.",
          sourceRefs: ["BEM Science archive 2016-2025"],
        },
      ],
    },
    {
      title: "البيئة والمنهجية",
      note: "سبب، أثر، حل.",
      questions: [
        {
          id: "sci-exam-env-1",
          type: "reorder",
          prompt: "رتبي منهجية حل وضعية بيئية:",
          items: ["الحل", "السبب", "الأثر"],
          correctOrder: ["السبب", "الأثر", "الحل"],
          hints: ["ابدئي بما أدى إلى المشكلة."],
          explanation: "هذا الترتيب يعطي جواباً منطقياً ومنظماً.",
          sourceRefs: ["BEM Science archive 2016-2025"],
        },
        {
          id: "sci-exam-env-2",
          type: "multiple-choice",
          prompt: "أي خيار يمثل حلاً بيئياً؟",
          choices: [
            { id: "a", label: "معالجة النفايات" },
            { id: "b", label: "زيادة التلوث" },
            { id: "c", label: "إهمال المحيط" },
          ],
          correctChoiceId: "a",
          hints: ["الحل يخفف المشكلة لا يزيدها."],
          explanation: "معالجة النفايات خطوة مباشرة للحد من التلوث.",
          sourceRefs: ["BEM Science archive 2016-2025"],
        },
      ],
    },
  ],
  islamic: [
    {
      title: "المعنى والقيمة",
      note: "فهم النص وتسمية القيمة المناسبة.",
      questions: [
        {
          id: "isl-exam-meaning-1",
          type: "multiple-choice",
          prompt: "إذا طلب السؤال قيمة أخلاقية، فأنت تبحثين عن...",
          choices: [
            { id: "a", label: "خلق مثل الصدق أو الأمانة" },
            { id: "b", label: "تاريخ سياسي" },
            { id: "c", label: "قانون رياضي" },
          ],
          correctChoiceId: "a",
          hints: ["القيمة ليست حدثاً ولا حساباً."],
          explanation: "القيمة الأخلاقية هي خلق أو سلوك يستفاد من النص.",
          sourceRefs: ["BEM Islamic archive 2016-2025"],
        },
        {
          id: "isl-exam-meaning-2",
          type: "short-text",
          prompt: "إذا كان النص يدعو إلى قول الحق، فما القيمة المناسبة؟",
          acceptedAnswers: ["الصدق", "صدق", "قيمة الصدق"],
          hints: ["فكري في الخلق المناسب."],
          explanation: "قول الحق يرتبط بقيمة الصدق.",
          sourceRefs: ["BEM Islamic archive 2016-2025"],
        },
      ],
    },
    {
      title: "العبرة والحكم",
      note: "ماذا نتعلم من النص؟",
      questions: [
        {
          id: "isl-exam-lesson-1",
          type: "short-text",
          prompt: "ما المقصود بالعبرة في الجواب؟",
          acceptedAnswers: [
            "الدرس المستفاد",
            "ما نتعلمه من النص",
            "الفائدة المستفادة",
          ],
          hints: ["العبرة ليست مجرد تكرار للمعنى."],
          explanation: "العبرة هي الدرس الذي نأخذه من النص ونطبقه.",
          sourceRefs: ["BEM Islamic archive 2016-2025"],
        },
        {
          id: "isl-exam-lesson-2",
          type: "multiple-choice",
          prompt: "أي جواب أقرب إلى العبرة؟",
          choices: [
            { id: "a", label: "نتعلم الصدق والابتعاد عن الكذب." },
            { id: "b", label: "هذا نص جميل فقط." },
            { id: "c", label: "الورقة بيضاء." },
          ],
          correctChoiceId: "a",
          hints: ["العبرة يجب أن تحمل فائدة عملية."],
          explanation: "العبرة القوية تربط النص بسلوك أو فائدة واضحة.",
          sourceRefs: ["BEM Islamic archive 2016-2025"],
        },
      ],
    },
    {
      title: "التطبيق",
      note: "تحويل القيمة إلى سلوك يومي واضح.",
      questions: [
        {
          id: "isl-exam-apply-1",
          type: "short-text",
          prompt: "كيف تطبقين الأمانة في الدراسة؟",
          acceptedAnswers: [
            "لا أغش وأؤدي واجباتي بصدق",
            "أبتعد عن الغش وأحافظ على الأمانة",
          ],
          hints: ["اذكري سلوكاً عملياً."],
          explanation: "الجواب الجيد يربط القيمة بسلوك واضح من الواقع.",
          sourceRefs: ["BEM Islamic archive 2016-2025"],
        },
        {
          id: "isl-exam-apply-2",
          type: "multiple-choice",
          prompt: "أي جواب تطبيقي أفضل؟",
          choices: [
            { id: "a", label: "أكون إنسانة جيدة." },
            { id: "b", label: "أقول الحقيقة وأتجنب الكذب." },
            { id: "c", label: "القيمة مهمة فقط." },
          ],
          correctChoiceId: "b",
          hints: ["الأفضل هو السلوك المحدد."],
          explanation: "التطبيق الأقوى يذكر فعلاً عملياً واضحاً.",
          sourceRefs: ["BEM Islamic archive 2016-2025"],
        },
      ],
    },
  ],
  civics: [
    {
      title: "الحقوق والواجبات",
      note: "تصنيف المفاهيم الأساسية بدقة.",
      questions: [
        {
          id: "civ-exam-rd-1",
          type: "multiple-choice",
          prompt: "التمدرس يمثل...",
          choices: [
            { id: "a", label: "حقاً" },
            { id: "b", label: "واجباً" },
            { id: "c", label: "مجرد رأي" },
          ],
          correctChoiceId: "a",
          hints: ["فكري في ما يستفيد منه المواطن."],
          explanation: "التمدرس من الحقوق الأساسية.",
          sourceRefs: ["BEM Civics archive 2016-2025"],
        },
        {
          id: "civ-exam-rd-2",
          type: "multiple-choice",
          prompt: "احترام القانون يمثل...",
          choices: [
            { id: "a", label: "حقاً" },
            { id: "b", label: "واجباً" },
            { id: "c", label: "لعبة" },
          ],
          correctChoiceId: "b",
          hints: ["هو ما يجب على المواطن فعله."],
          explanation: "احترام القانون من واجبات المواطن.",
          sourceRefs: ["BEM Civics archive 2016-2025"],
        },
      ],
    },
    {
      title: "المؤسسات",
      note: "اسم المؤسسة مع دورها.",
      questions: [
        {
          id: "civ-exam-inst-1",
          type: "short-text",
          prompt: "بعد تسمية المؤسسة، ما الذي ينبغي ذكره غالباً؟",
          acceptedAnswers: ["دورها", "الوظيفة", "دور المؤسسة"],
          hints: ["الاسم وحده لا يكفي."],
          explanation: "الجواب الأقوى يذكر المؤسسة ثم دورها أو وظيفتها.",
          sourceRefs: ["BEM Civics archive 2016-2025"],
        },
        {
          id: "civ-exam-inst-2",
          type: "multiple-choice",
          prompt: "أي جواب أفضل؟",
          choices: [
            { id: "a", label: "البلدية فقط." },
            { id: "b", label: "البلدية مؤسسة محلية تقدم خدمات للمواطن." },
            { id: "c", label: "شيء في الحي." },
          ],
          correctChoiceId: "b",
          hints: ["الأفضل يجمع الاسم والدور."],
          explanation: "الجواب الجيد يربط المؤسسة بوظيفتها مباشرة.",
          sourceRefs: ["BEM Civics archive 2016-2025"],
        },
      ],
    },
    {
      title: "وضعية إدماجية قصيرة",
      note: "تنظيم الجواب في سيناريو بسيط.",
      questions: [
        {
          id: "civ-exam-case-1",
          type: "reorder",
          prompt: "رتبي بناء الجواب:",
          items: ["فائدة أو أثر", "تعريف قصير", "مثال مناسب"],
          correctOrder: ["تعريف قصير", "مثال مناسب", "فائدة أو أثر"],
          hints: ["ابدئي بالمفهوم ثم التطبيق."],
          explanation: "هذا الترتيب يجعل الجواب أوضح وأكثر إقناعاً.",
          sourceRefs: ["BEM Civics archive 2016-2025"],
        },
        {
          id: "civ-exam-case-2",
          type: "short-text",
          prompt: "أعطي مثالاً واحداً على سلوك مواطن صالح.",
          acceptedAnswers: [
            "يحترم القانون",
            "يحافظ على الممتلكات العامة",
            "يشارك بإيجابية",
          ],
          hints: ["اختاري سلوكاً عملياً من الواقع."],
          explanation: "الأمثلة اليومية تثبت المفهوم وتدعم الجواب.",
          sourceRefs: ["BEM Civics archive 2016-2025"],
        },
      ],
    },
  ],
};

export function buildGuidedExamSections(subjectId: SubjectId) {
  return guidedExamSections[subjectId] ?? [];
}
